# Pre-commit configuration for Terraform code formatting and validation used locally.
minimum_pre_commit_version: "4"
fail_fast: false
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0 # sha256:4ef4b8323b27fc263535ad88c9d2f20488fcb3b520258e5e7f0553ed5f6692b5
    hooks:
      - id: terraform_fmt
        name: Terraform fmt
        files: \.(tf|tfvars)$
        args:
          - --args=-check
          - --args=-diff
          - --args=-recursive
          - --args=-write=false

      - id: terraform_validate
        name: Terraform validate
        files: \.tf$
        args:
          - --args=-no-color
          - --tf-init-args=-backend=false
          - --tf-init-args=-input=false
          - --tf-init-args=-no-color
          - --hook-config=--parallelism-limit=1

      - id: terraform_tflint
        name: Terraform TFLint
        files: \.tf$
        args:
          - --args=--format=compact
          - --args=--no-color
          - --args=--minimum-failure-severity=warning
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl