apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xray-daemon
  name: xray-daemon
  namespace: ${namespace}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xray-daemon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xray-daemon
    spec:
      containers:
      - image: amazon/aws-xray-daemon:${xray_daemon_img_version}
        imagePullPolicy: Always
        args: ["-o"]
        name: xray-daemon
        ports:
        - containerPort: 2000
          protocol: UDP
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 150m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: ${xray_daemon_service_account}
      terminationGracePeriodSeconds: 30