apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: xray-daemon
  namespace: ${namespace}
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xray-daemon
  targetCPUUtilizationPercentage: 70