apiVersion: v1
kind: Service
metadata:
  labels:
    app: xray-daemon
  name: xray-daemon
  namespace: ${namespace}
spec:
  ports:
  - name: "udp"
    port: 2001
    protocol: UDP
    targetPort: 2000
  - name: "tcp"
    port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app: xray-daemon
  type: ClusterIP