apiVersion: v1
kind: Service
metadata:
  labels:
    app: xray-daemon
  name: xray-daemon
  namespace: ${namespace}
spec:
  ports:
  - name: "http"
    port: 80
    protocol: UDP
    targetPort: 2000
  selector:
    app: xray-daemon
  type: NodePort